### ISSUE TITLE
Pre check not found

### ISSUE THREAD

**Issue by atatarenko** [palkan/action_policy#156]
### Tell us about your environment

**Ruby Version:**  2.7

**Framework Version (Rails, whatever):**  4.2.11.3

**Action Policy Version:**  0.4.4

**Reproduction Script:** It failed to run because of the "uninitialized constant" error it got in the app configuration. I was kinda lazy to dive into that until this is really needed 🙃 . Perhaps, this is not that necessary.

### What did you do?
It's easier to explain with code

```ruby
class ApplicationPolicy
  ...
  pre_check :allow_org_admins
  ...
  
  def allow_org_admins
    allow! if admin?
  end
end

class SomePolicy < ApplicationPolicy
  ...
  skip_pre_check :allow_org_admins
  ...
  
  def delete?
     ...
  end
end
```

Then it just gets run
```ruby
authorize! some_object, to: :delete?
```

### What did you expect to happen?

The `allow_org_admins` pre-check defined in the superclass is just skipped.

### What actually happened?

Most of the time it behaves as expected, in tests, in the console, it works just fine. However, this is what I recently found in the production logs:

```
RuntimeError: Pre-check not found: allow_org_admins ["/bundle/gems/action_policy-0.4.4/lib/action_policy/policy/pre_check.rb:178:in `block in skip_pre_check'", "/bundle/gems/action_policy-0.4.4/lib/action_policy/policy/pre_check.rb:176:in `each'", "/bundle/gems/action_policy-0.4.4/lib/action_policy/policy/pre_check.rb:176:in `skip_pre_check'", "/app/policies/some_policy.rb:8:in `<class:SomePolicy>'",
```

Maybe this happens because of inheritance, no idea because there is no solid way to reproduce it constantly. I simplified something so let me know if you need other details.

**Comment by atatarenko** [comment]
**UPD**

Now I see that missed the important detail. It's that code was being executed via cron and rake task. I added `require 'action_policy'` at the top of the ApplicationPolicy file and then I got a couple of errors like below:
```
NameError: uninitialized constant ActionPolicy::ScopeMatchers::ActiveRecord
NameError: uninitialized constant ActionPolicy::ScopeMatchers::ActionControllerParams
```

Then I also explicitly required those two, so the final change I made is
```diff
+require 'action_policy'
+require 'action_policy/rails/scope_matchers/active_record'
+require 'action_policy/rails/scope_matchers/action_controller_params'

class ApplicationPolicy
   ...
end
```

I suspect there might be something that with dependencies load here

https://github.com/palkan/action_policy/blob/c9a4a5dc325da02bac9296be6a136aa89b4649ec/lib/action_policy.rb#L47

And here

https://github.com/palkan/action_policy/blob/c9a4a5dc325da02bac9296be6a136aa89b4649ec/lib/action_policy/railtie.rb#L105-L108

But at this very point, I'm going to stop researches as my issue has been solved.
