### ISSUE TITLE
undefined method `relation_scope'

### ISSUE THREAD

**Issue by lifeiscontent** [palkan/action_policy#200]
Hey @palkan hope you've been well.

I've been trying to get my app redeployed after a recent upgrade and I keep running into an issue saying:

```
undefined method `relation_scope'
```

here's the logs from the last build:

```
-----> Building on the Heroku-20 stack
-----> Using buildpack: https://github.com/Pagedraw/heroku-buildpack-select-subdir
-----> Multipack looking for subdirectory app detected
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-ruby, branch: , to tmp dir /tmp/buildpackqyBf5, against source's subdir: api
=====> Detected Framework: Ruby
-----> Installing bundler 2.2.21
-----> Removing BUNDLED WITH version in the Gemfile.lock
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.7.5
-----> Installing dependencies using bundler 2.2.21
       Running: BUNDLE_WITHOUT='development:test' BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 bundle install -j4
       Fetching gem metadata from https://rubygems.org/
       Fetching gem metadata from https://rubygems.org/..........
       Using rake 13.0.6
       Using ruby-next-core 0.13.2
       Using graphql 1.13.0
       Using concurrent-ruby 1.1.9
       Using minitest 5.14.4
       Using zeitwerk 2.5.1
       Using builder 3.2.4
       Using erubi 1.10.0
       Using mini_portile2 2.6.1
       Using racc 1.6.0
       Using crass 1.0.6
       Using rack 2.2.3
       Using nio4r 2.5.8
       Using websocket-extensions 0.1.5
       Using marcel 1.0.2
       Using mini_mime 1.1.2
       Using bcrypt 3.1.16
       Using msgpack 1.4.2
       Using bundler 2.2.21
       Using orm_adapter 0.5.0
       Using thor 1.1.0
       Using method_source 1.0.0
       Using jwt 2.3.0
       Using pg 1.2.3
       Using i18n 1.8.11
       Using tzinfo 2.0.4
       Using nokogiri 1.12.5 (x86_64-linux)
       Fetching action_policy 0.5.7
       Using puma 5.5.2
       Using websocket-driver 0.7.5
       Using rack-test 1.1.0
       Using mail 2.7.1
       Using warden 1.2.9
       Using rack-cors 1.1.1
       Using sprockets 4.0.2
       Using bootsnap 1.9.3
       Using loofah 2.12.0
       Using activesupport 6.1.4.1
       Using faker 2.19.0
       Using rails-dom-testing 2.0.3
       Using rails-html-sanitizer 1.4.2
       Using globalid 1.0.0
       Using activemodel 6.1.4.1
       Using actionview 6.1.4.1
       Using activejob 6.1.4.1
       Using actionpack 6.1.4.1
       Using activerecord 6.1.4.1
       Installing action_policy 0.5.7
       Using actioncable 6.1.4.1
       Using activestorage 6.1.4.1
       Using actionmailer 6.1.4.1
       Using railties 6.1.4.1
       Using friendly_id 5.4.2
       Using sprockets-rails 3.4.1
       Using actionmailbox 6.1.4.1
       Using actiontext 6.1.4.1
       Using responders 3.0.1
       Using rails 6.1.4.1
       Using devise 4.8.0
       Using action_policy-graphql 0.5.3
       Bundle complete! 25 Gemfile dependencies, 59 gems now installed.
       Gems in the groups 'development' and 'test' were not installed.
       Bundled gems are installed into `./vendor/bundle`
       Bundle completed (1.98s)
       Cleaning up the bundler cache.
       Removing action_policy (0.6.0)
-----> Detecting rake tasks
-----> Detecting rails configuration
       $ rails runner "begin; puts %Q{heroku.detecting.config.for.assets.compile=#{Rails.application.config.try(:assets).try(:compile)}}; rescue => e; puts e; puts e.backtrace; end; begin; puts %Q{heroku.detecting.config.for.action_dispatch.x_sendfile_header=#{Rails.application.config.try(:action_dispatch).try(:x_sendfile_header)}}; rescue => e; puts e; puts e.backtrace; end;"
       /tmp/build_0ac03ddc/api/app/policies/article_feed_policy.rb:4:in `<class:ArticleFeedPolicy>': undefined method `relation_scope' for ArticleFeedPolicy:Class (NoMethodError)
       	from /tmp/build_0ac03ddc/api/app/policies/article_feed_policy.rb:3:in `<main>'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:27:in `require'
       	from /tmp/build_0ac03ddc/api/app/graphql/types/query_type.rb:5:in `<class:QueryType>'
       	from /tmp/build_0ac03ddc/api/app/graphql/types/query_type.rb:4:in `<module:Types>'
       	from /tmp/build_0ac03ddc/api/app/graphql/types/query_type.rb:3:in `<main>'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:27:in `require'
       	from /tmp/build_0ac03ddc/api/app/graphql/api_schema.rb:5:in `<class:ApiSchema>'
       	from /tmp/build_0ac03ddc/api/app/graphql/api_schema.rb:3:in `<main>'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:27:in `require'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:95:in `const_get'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:95:in `cget'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:232:in `block (2 levels) in eager_load'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:18:in `ls'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:227:in `block in eager_load'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:212:in `synchronize'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:212:in `eager_load'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:312:in `each'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:312:in `eager_load_all'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.1/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.1/lib/rails/initializable.rb:32:in `instance_exec'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.1/lib/rails/initializable.rb:32:in `run'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.1/lib/rails/initializable.rb:61:in `block in run_initializers'
       	from /tmp/build_0ac03ddc/api/vendor/ruby-2.7.5/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
       	from /tmp/build_0ac03ddc/api/vendor/ruby-2.7.5/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
       	from /tmp/build_0ac03ddc/api/vendor/ruby-2.7.5/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
       	from /tmp/build_0ac03ddc/api/vendor/ruby-2.7.5/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
       	from /tmp/build_0ac03ddc/api/vendor/ruby-2.7.5/lib/ruby/2.7.0/tsort.rb:347:in `each'
       	from /tmp/build_0ac03ddc/api/vendor/ruby-2.7.5/lib/ruby/2.7.0/tsort.rb:347:in `call'
       	from /tmp/build_0ac03ddc/api/vendor/ruby-2.7.5/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
       	from /tmp/build_0ac03ddc/api/vendor/ruby-2.7.5/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
       	from /tmp/build_0ac03ddc/api/vendor/ruby-2.7.5/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.1/lib/rails/initializable.rb:60:in `run_initializers'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.1/lib/rails/application.rb:391:in `initialize!'
       	from /tmp/build_0ac03ddc/api/config/environment.rb:5:in `<main>'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.1/lib/rails/application.rb:367:in `require_environment!'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.1/lib/rails/command/actions.rb:28:in `require_environment!'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.1/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.1/lib/rails/commands/runner/runner_command.rb:33:in `perform'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.1/lib/rails/command/base.rb:69:in `perform'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.1/lib/rails/command.rb:48:in `invoke'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.1/lib/rails/commands.rb:18:in `<main>'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
       	from /tmp/build_0ac03ddc/api/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
       	from /tmp/build_0ac03ddc/api/bin/rails:5:in `<main>'
###### WARNING:
       Detecting rails configuration failed
Copying Procfile...
Creating .profile.d...
-----> Discovering process types
       Procfile declares types -> web
-----> Compressing...
       Done: 32M
-----> Launching...
       Released v581
       https://realworld-api-production.herokuapp.com/ deployed to Heroku
```

and if you have a moment, you can take a look at the code here: https://github.com/lifeiscontent/realworld

### Tell us about your environment

**Ruby Version:**

**Framework Version (Rails, whatever):**

**Action Policy Version:**

**Reproduction Script:** Use [this template](https://github.com/palkan/action_policy/blob/master/.github/bug_report_template.rb) to
create a standalone reproduction script. That would help us to fix the problem quicker. Thanks!

**Comment by palkan** [comment]
> after a recent upgrade and I keep running into an issue

So, this started to happen after you upgraded action_policy or other deps?
Could you please provide the Gemfile.lock diff between the last working and the current versions?

**Comment by erickreutz** [comment]
I had this same problem. My guess is you are using a custom base policy and reading the source code they extend their internal base policy to set up the active record scoping which is not specified in their docs regarding using a custom base policy. 

I had to add the following to my custom base policy to get it working correctly.

```ruby
module Policies
  class BasePolicy
    include ActionPolicy::Policy::Core
    include ActionPolicy::Policy::Authorization
    include ActionPolicy::Policy::PreCheck
    include ActionPolicy::Policy::Reasons
    include ActionPolicy::Policy::Aliases
    include ActionPolicy::Policy::Scoping
    include ActionPolicy::Policy::Cache
    include ActionPolicy::Policy::CachedApply
    include ActionPolicy::Policy::Defaults

    # These additions
    extend ActionPolicy::ScopeMatchers::ActiveRecord
    scope_matcher :active_record_relation, ActiveRecord::Relation
  end
end
```

**Comment by palkan** [comment]
Thanks! 
Updated the docs: https://github.com/palkan/action_policy/commit/cbab6c8f5ff6e478b90f010f6d81b11c41e7a9fc
