### ISSUE TITLE
Support Rails-compatible cache initialization

### ISSUE THREAD

**Issue by alaz** [palkan/action_policy#39]
### Tell us about your environment

**Ruby Version: 2.5**

**Framework Version (Rails, whatever): Rails 5.2.1**

**Action Policy Version: 0.2.3**

### What did you do?

I have initialized Action Policy's cache in exactly the same way as [Rails documentation recommends](https://guides.rubyonrails.org/caching_with_rails.html#activesupport-cache-memcachestore):

```
config.action_policy.cache_store = :mem_cache_store, ENV['MEMCACHE_SERVERS'], {namespace: "r2", compress: true, pool: 32}
```

### What actually happened?

Exception:

```
vendor/bundle/jruby/2.5.0/gems/action_policy-0.2.3/lib/action_policy/policy/cache.rb:45:in `block in apply_with_cache': undefined method `read' for #<Array:0xd0fabc8> (NoMethodError)
    from org/jruby/RubyKernel.java:1301:in `yield_self'
    from vendor/bundle/jruby/2.5.0/gems/action_policy-0.2.3/lib/action_policy/policy/cache.rb:44:in `apply_with_cache'
    from vendor/bundle/jruby/2.5.0/gems/action_policy-0.2.3/lib/action_policy/policy/cache.rb:58:in `apply'
    from vendor/bundle/jruby/2.5.0/gems/action_policy-0.2.3/lib/action_policy/policy/cached_apply.rb:18:in `apply'
    from vendor/bundle/jruby/2.5.0/gems/action_policy-0.2.3/lib/action_policy/policy/reasons.rb:98:in `allowed_to?'
    from app/policies/topic_policy.rb:7:in `show?'

```

**Comment by palkan** [comment]
Thanks for the report!

Just pushed a fix to master, check, please.

**Comment by alaz** [comment]
Fixed. Thank you!
